// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         name: "Tropical Rainforest Conservation",
 *         description: "A project focused on preserving tropical rainforest biodiversity."
 *     }
 */
export interface CreateProjectRequest {
    name: string;
    description?: string | null;
}
