// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         projectId: "proj_9f8d7c2a"
 *     }
 */
export interface DeleteProjectRequest {
    projectId: string;
}
