// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         projectId: "proj_9f8b7c6d"
 *     }
 */
export interface GetProjectRequest {
    projectId: string;
}
