// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListProjectsRequest {
    /** Number of projects to skip */
    skip?: number;
    /** Maximum number of projects to return */
    limit?: number;
}
