// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         projectId: "proj_9f8b7c6d",
 *         name: "Tropical Rainforest Conservation",
 *         description: "A project focused on preserving the biodiversity of tropical rainforests."
 *     }
 */
export interface UpdateProjectRequest {
    projectId: string;
    name?: string | null;
    description?: string | null;
}
