// This file was auto-generated by Fern from our API Definition.

/** Document processing status */
export const DocumentStatus = {
    Uploaded: "uploaded",
    Queued: "queued",
    Processing: "processing",
    Ready: "ready",
    Error: "error",
} as const;
export type DocumentStatus = (typeof DocumentStatus)[keyof typeof DocumentStatus];
