// This file was auto-generated by Fern from our API Definition.

import type * as tropicalia from "../index.js";

export interface Document {
    id: string;
    filename: string;
    /** File size in bytes */
    file_size: number;
    status: tropicalia.DocumentStatus;
    created_at: string;
    modified_at: string;
}
