// This file was auto-generated by Fern from our API Definition.

export const RetrievalStrategy = {
    Hybrid: "hybrid",
    Neural: "neural",
    Keyword: "keyword",
} as const;
export type RetrievalStrategy = (typeof RetrievalStrategy)[keyof typeof RetrievalStrategy];
