// This file was auto-generated by Fern from our API Definition.

export interface RetrievalMetadata {
    /** Extracted title from document */
    document_title?: string;
    /** Source document UUID */
    document_id: string;
    /** Original filename */
    file_name: string;
    /** Content type */
    type: RetrievalMetadata.Type;
    /** Position of chunk within document */
    chunk_index: number;
    /** Token count of the chunk */
    chunk_size?: number;
    /** JSON array of page numbers (e.g. "[1, 2]") */
    page?: string;
    /** When the chunk was indexed */
    date_created: string;
}

export namespace RetrievalMetadata {
    /** Content type */
    export const Type = {
        Chunk: "chunk",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
