// This file was auto-generated by Fern from our API Definition.

import type * as tropicalia from "../index.js";

export interface RetrievalContent {
    /** Citation position [[N]] */
    number: number;
    /** Chroma vector ID */
    id: string;
    /** Text content of the chunk */
    document: string;
    /** Relevance score */
    score: number;
    /** Rerank relevance score (only present when rerank is enabled) */
    rerank_score?: number | null;
    metadata: tropicalia.RetrievalMetadata;
}
