// This file was auto-generated by Fern from our API Definition.

import type * as tropicalia from "../index.js";

export interface SearchResponse {
    /** AI-generated answer (when generate_answer is true) */
    completion?: string | null;
    retrieval_contents: tropicalia.RetrievalContent[];
}
