// This file was auto-generated by Fern from our API Definition.

import type * as tropicalia from "../../index.js";

/**
 * @example
 *     {
 *         projectId: "proj_9f8b7c6d",
 *         query: "Best practices for sustainable tropical agriculture",
 *         retrieval_strategy: "hybrid",
 *         expand_query: false,
 *         rerank: true,
 *         generate_answer: true,
 *         include_sources: true,
 *         limit: 50
 *     }
 */
export interface SearchRequest {
    /** Project ID to search within */
    projectId: string;
    /** Search query text (max 2048 tokens) */
    query: string;
    retrieval_strategy?: tropicalia.RetrievalStrategy;
    /** Generate query variations to improve recall */
    expand_query?: boolean;
    /** Rerank results using Cohere for improved relevance */
    rerank?: boolean;
    /** Generate a natural-language answer */
    generate_answer?: boolean;
    /** Include source documents in response. Set false to reduce payload when only the answer is needed. */
    include_sources?: boolean;
    /** Maximum results to return */
    limit?: number;
}
