// This file was auto-generated by Fern from our API Definition.

import { tropicaliaClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("tropicaliaClient", () => {
    test("Search", async () => {
        const server = mockServerPool.createServer();
        const client = new tropicaliaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            query: "Best practices for sustainable tropical agriculture",
            retrieval_strategy: "hybrid",
            expand_query: false,
            rerank: true,
            generate_answer: true,
            include_sources: true,
            limit: 50,
        };
        const rawResponseBody = {
            completion:
                "Sustainable tropical agriculture involves crop diversification, soil conservation, and integrated pest management to maintain ecosystem health and productivity.",
            retrieval_contents: [
                {
                    number: 1,
                    id: "a3f1c9d2-4b7e-4f8a-9c3d-2e5b7f6a1d9e",
                    document:
                        "Sustainable tropical agriculture focuses on methods that preserve soil fertility and biodiversity while maximizing crop yields.",
                    score: 0.92,
                    rerank_score: 0.95,
                    metadata: {
                        document_title: "Sustainable Farming Techniques in Tropical Regions",
                        document_id: "d4e5f6a7-b8c9-4d0e-9f1a-2b3c4d5e6f7a",
                        file_name: "sustainable_farming_tropics.pdf",
                        type: "chunk",
                        chunk_index: 3,
                        chunk_size: 512,
                        page: "[12, 13]",
                        date_created: "2024-01-15T09:30:00Z",
                    },
                },
            ],
        };
        server
            .mockEndpoint()
            .post("/v1/projects/proj_9f8b7c6d/search")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.search({
            projectId: "proj_9f8b7c6d",
            query: "Best practices for sustainable tropical agriculture",
            retrieval_strategy: "hybrid",
            expand_query: false,
            rerank: true,
            generate_answer: true,
            include_sources: true,
            limit: 50,
        });
        expect(response).toEqual({
            completion:
                "Sustainable tropical agriculture involves crop diversification, soil conservation, and integrated pest management to maintain ecosystem health and productivity.",
            retrieval_contents: [
                {
                    number: 1,
                    id: "a3f1c9d2-4b7e-4f8a-9c3d-2e5b7f6a1d9e",
                    document:
                        "Sustainable tropical agriculture focuses on methods that preserve soil fertility and biodiversity while maximizing crop yields.",
                    score: 0.92,
                    rerank_score: 0.95,
                    metadata: {
                        document_title: "Sustainable Farming Techniques in Tropical Regions",
                        document_id: "d4e5f6a7-b8c9-4d0e-9f1a-2b3c4d5e6f7a",
                        file_name: "sustainable_farming_tropics.pdf",
                        type: "chunk",
                        chunk_index: 3,
                        chunk_size: 512,
                        page: "[12, 13]",
                        date_created: "2024-01-15T09:30:00Z",
                    },
                },
            ],
        });
    });
});
