// This file was auto-generated by Fern from our API Definition.

import { tropicaliaClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ProjectsClient", () => {
    test("listProjects", async () => {
        const server = mockServerPool.createServer();
        const client = new tropicaliaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = [
            {
                public_id: "proj_9f8b7c6d",
                name: "Tropical Rainforest Conservation",
                description: "A project focused on preserving endangered rainforest species",
                created_at: "2024-04-10T08:45:00Z",
                modified_at: "2024-05-01T12:00:00Z",
            },
            {
                public_id: "proj_4a3d2e1f",
                name: "Coral Reef Restoration",
                description: "Initiative to restore damaged coral reefs in the Caribbean",
                created_at: "2023-11-20T14:20:00Z",
                modified_at: "2024-04-15T09:30:00Z",
            },
        ];
        server.mockEndpoint().get("/v1/projects").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.projects.listProjects();
        expect(response).toEqual([
            {
                public_id: "proj_9f8b7c6d",
                name: "Tropical Rainforest Conservation",
                description: "A project focused on preserving endangered rainforest species",
                created_at: "2024-04-10T08:45:00Z",
                modified_at: "2024-05-01T12:00:00Z",
            },
            {
                public_id: "proj_4a3d2e1f",
                name: "Coral Reef Restoration",
                description: "Initiative to restore damaged coral reefs in the Caribbean",
                created_at: "2023-11-20T14:20:00Z",
                modified_at: "2024-04-15T09:30:00Z",
            },
        ]);
    });

    test("createProject", async () => {
        const server = mockServerPool.createServer();
        const client = new tropicaliaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            name: "Tropical Rainforest Conservation",
            description: "A project focused on preserving tropical rainforest biodiversity.",
        };
        const rawResponseBody = {
            public_id: "proj_trf2024",
            name: "Tropical Rainforest Conservation",
            description: "A project focused on preserving tropical rainforest biodiversity.",
            created_at: "2024-04-10T08:45:00Z",
            modified_at: "2024-04-10T08:45:00Z",
        };
        server
            .mockEndpoint()
            .post("/v1/projects")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.projects.createProject({
            name: "Tropical Rainforest Conservation",
            description: "A project focused on preserving tropical rainforest biodiversity.",
        });
        expect(response).toEqual({
            public_id: "proj_trf2024",
            name: "Tropical Rainforest Conservation",
            description: "A project focused on preserving tropical rainforest biodiversity.",
            created_at: "2024-04-10T08:45:00Z",
            modified_at: "2024-04-10T08:45:00Z",
        });
    });

    test("getProject", async () => {
        const server = mockServerPool.createServer();
        const client = new tropicaliaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            public_id: "proj_9f8b7c6d",
            name: "Tropical Rainforest Conservation",
            description: "A project focused on preserving biodiversity in the Amazon rainforest.",
            created_at: "2024-04-10T08:45:00Z",
            modified_at: "2024-05-01T14:20:00Z",
        };
        server
            .mockEndpoint()
            .get("/v1/projects/proj_9f8b7c6d")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.projects.getProject({
            projectId: "proj_9f8b7c6d",
        });
        expect(response).toEqual({
            public_id: "proj_9f8b7c6d",
            name: "Tropical Rainforest Conservation",
            description: "A project focused on preserving biodiversity in the Amazon rainforest.",
            created_at: "2024-04-10T08:45:00Z",
            modified_at: "2024-05-01T14:20:00Z",
        });
    });

    test("updateProject", async () => {
        const server = mockServerPool.createServer();
        const client = new tropicaliaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            name: "Tropical Rainforest Conservation",
            description: "A project focused on preserving the biodiversity of tropical rainforests.",
        };
        const rawResponseBody = {
            public_id: "proj_9f8b7c6d",
            name: "Tropical Rainforest Conservation",
            description: "A project focused on preserving the biodiversity of tropical rainforests.",
            created_at: "2024-01-15T09:30:00Z",
            modified_at: "2024-04-20T16:45:00Z",
        };
        server
            .mockEndpoint()
            .put("/v1/projects/proj_9f8b7c6d")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.projects.updateProject({
            projectId: "proj_9f8b7c6d",
            name: "Tropical Rainforest Conservation",
            description: "A project focused on preserving the biodiversity of tropical rainforests.",
        });
        expect(response).toEqual({
            public_id: "proj_9f8b7c6d",
            name: "Tropical Rainforest Conservation",
            description: "A project focused on preserving the biodiversity of tropical rainforests.",
            created_at: "2024-01-15T09:30:00Z",
            modified_at: "2024-04-20T16:45:00Z",
        });
    });

    test("deleteProject", async () => {
        const server = mockServerPool.createServer();
        const client = new tropicaliaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { public_id: "proj_9f8d7c2a", deleted: true };
        server
            .mockEndpoint()
            .delete("/v1/projects/proj_9f8d7c2a")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.projects.deleteProject({
            projectId: "proj_9f8d7c2a",
        });
        expect(response).toEqual({
            public_id: "proj_9f8d7c2a",
            deleted: true,
        });
    });
});
