// This file was auto-generated by Fern from our API Definition.

import { tropicaliaClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("UploadClient", () => {
    test("listDocuments", async () => {
        const server = mockServerPool.createServer();
        const client = new tropicaliaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = [
            {
                id: "a3f1c2d4-5b6e-7f89-0123-456789abcdef",
                filename: "project-proposal.pdf",
                file_size: 2457600,
                status: "ready",
                created_at: "2024-04-10T14:22:00Z",
                modified_at: "2024-04-12T08:15:00Z",
            },
            {
                id: "b7d9e8f0-1234-5678-9abc-def012345678",
                filename: "budget.xlsx",
                file_size: 512000,
                status: "processing",
                created_at: "2024-04-11T09:00:00Z",
                modified_at: "2024-04-11T10:30:00Z",
            },
            {
                id: "c1d2e3f4-5678-9abc-def0-123456789abc",
                filename: "meeting-notes.docx",
                file_size: 102400,
                status: "uploaded",
                created_at: "2024-04-09T16:45:00Z",
                modified_at: "2024-04-09T16:45:00Z",
            },
        ];
        server
            .mockEndpoint()
            .get("/v1/projects/proj_9f8b7c6d5e4a3b2c1d0e/documents")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.upload.listDocuments({
            projectId: "proj_9f8b7c6d5e4a3b2c1d0e",
        });
        expect(response).toEqual([
            {
                id: "a3f1c2d4-5b6e-7f89-0123-456789abcdef",
                filename: "project-proposal.pdf",
                file_size: 2457600,
                status: "ready",
                created_at: "2024-04-10T14:22:00Z",
                modified_at: "2024-04-12T08:15:00Z",
            },
            {
                id: "b7d9e8f0-1234-5678-9abc-def012345678",
                filename: "budget.xlsx",
                file_size: 512000,
                status: "processing",
                created_at: "2024-04-11T09:00:00Z",
                modified_at: "2024-04-11T10:30:00Z",
            },
            {
                id: "c1d2e3f4-5678-9abc-def0-123456789abc",
                filename: "meeting-notes.docx",
                file_size: 102400,
                status: "uploaded",
                created_at: "2024-04-09T16:45:00Z",
                modified_at: "2024-04-09T16:45:00Z",
            },
        ]);
    });

    test("deleteDocument", async () => {
        const server = mockServerPool.createServer();
        const client = new tropicaliaClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { id: "3fa85f64-5717-4562-b3fc-2c963f66afa6", deleted: true };
        server
            .mockEndpoint()
            .delete("/v1/projects/proj_9f8b7c6d5e4a3b2c1d0e/documents/3fa85f64-5717-4562-b3fc-2c963f66afa6")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.upload.deleteDocument({
            projectId: "proj_9f8b7c6d5e4a3b2c1d0e",
            documentId: "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        });
        expect(response).toEqual({
            id: "3fa85f64-5717-4562-b3fc-2c963f66afa6",
            deleted: true,
        });
    });
});
