// This file was auto-generated by Fern from our API Definition.

export const tropicaliaEnvironment = {
    Production: "https://api.tropicalia.dev",
} as const;

export type tropicaliaEnvironment = typeof tropicaliaEnvironment.Production;
