// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         projectId: "proj_9f8b7c6d5e4a3b2c1d0e",
 *         documentId: "3fa85f64-5717-4562-b3fc-2c963f66afa6"
 *     }
 */
export interface DeleteDocumentRequest {
    projectId: string;
    documentId: string;
}
