// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         projectId: "proj_9f8b7c6d5e4a3b2c1d0e"
 *     }
 */
export interface ListDocumentsRequest {
    projectId: string;
    /** Number of documents to skip */
    skip?: number;
    /** Maximum number of documents to return */
    limit?: number;
}
