// This file was auto-generated by Fern from our API Definition.

import type * as core from "../../../../../core/index.js";

/**
 * @example
 *     {
 *         file: fs.createReadStream("/path/to/your/file"),
 *         projectId: "projectId"
 *     }
 */
export interface UploadFileRequest {
    /** Project ID to upload the file to */
    projectId: string;
    /** File to upload (max 100MB) */
    file: core.file.Uploadable;
}
